[project]
name = "mcp-server-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "fastapi-mcp>=0.3.4",
    "mcp[cli]>=1.9.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
